[[protoc]]
arch = "aarch64"
git-tree-sha1 = "a316b34830342f983ae231c7ad3ac5fce4dd7c49"
os = "macos"

    [[protoc.download]]
    sha256 = "b4af3d8ae33b0ab410ee98b686b567b45e6fcf99cabc4630e11bbe234a019a38"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.aarch64-apple-darwin.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ccdc38f6a28f1c8f8ed6a6602ca10910fe621f0"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "05a29ed43f1f7a35c24e0f811aefb16c0f8ffc3d0d840c09ee0425bd44115fd5"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.aarch64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "727bc404b2944ee20a50261b75d20de5fbf5ed0b"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "267001206408e1a2cf1dc69918f64d2eef23b997e127856cff2f5ebf1fbf6a6c"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.aarch64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7bd704016b8bc665b44ef91b0e07287ec8e843b"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "48bc3d0689f60646f77e5a7f5fb6d7b28dab77d38e90604dbc4bf56a10efb8d8"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.aarch64-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9032bce76e77ac6d9f3bafcc90e9be755a36522c"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "bee138bafb15009fbe9a46f91fcfb2b782ede158325c2ea7d8a6c10c02bd968e"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.aarch64-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69a192f0377435a03a0b15aa349d9571468a2ae1"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "63ba164bcd76af28166f902a08fdeb49b9402eb26cdbeb067ab3ee67e43ad7a0"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e6c49052ee7ca505d81639b20f79dabbb262d9e"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "18156d3c8b3f0d6830507dbf947a7411b5a9d0eb18f2e1bce3015246cd9e8216"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72faa59b0f09a75b4d165bc7885a0bd21bad0db5"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "ad81b3514756c38c920fc9fdb59029788f439a12f0192ab0e4aed636ba6935bc"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.armv6l-linux-musleabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "671aa48e41cfc19cba7a018b98eeb50141258afb"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "98107a931fb1f95ccb214e0215376a899d6d582aa5ec8f34fe4c5d44d0cce95c"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1da45c54698c7e68b00dfdb54a25ec0e8651316c"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "bce7d9d8fa816f8e7bf764074989760d80ffac486624220c553b008b058d0278"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b44667e083fbdab932907bdaa2c0e0f61c57cdb"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "e817d9c7825326fa293da0d0e25a8234bc3d8894438693bcf5dc6383a42382bb"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf079b3dbf1ff643074da99f7cfa8457c2bc287e"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "24a1d01c447c54fd6e5af07129f4f2be57c3f8e769c0157a92f0fa8d03534e52"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0bb77f7cdbd2bc57b140781c95044ad0e163915"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "63374df565c1437c6aba4da2ddb404cc004b16302a415c3e7f6d52cf1014a388"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f13a38ee27c8790872329eb37333ef155329061b"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "f055c536de7f27fad0f16134b257179f26910cb88fca2c1e91f27edf73f78465"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.i686-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4323c1e5d4a03ce247869ce98531f2fc4ba2c03a"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "e519729d7da070b28a9a3ff150e153a23da229548bcc01fffdf724df09f30544"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.i686-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2a83cfac9d68fc90452f6e3e7abb6c8027d53fc"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "a1fe1003ab555748b417da8f034acf937b1638c1896139f71479bdc3dc10a0ed"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.i686-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c27b757e26548500a6de6cfdf78f3bf845ee1b91"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "4f28ad802f5322e749d36a33fd3b3a31fed2f9e4be12fa8198729949d24f63c8"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.i686-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c5483051ba3096199cf7d98a1262c26fadf9cfd"
os = "windows"

    [[protoc.download]]
    sha256 = "50014a256762e1a02523ae31b3a84ba49d3f5fa488b1b0a457628eaca2ee1522"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.i686-w64-mingw32-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf2819df4eedaed7b4b847faca86c7dac0adccd2"
os = "windows"

    [[protoc.download]]
    sha256 = "128524791cf3a7220963e95dc6b7be0b704c9fbb001a087f51c929a6822f3671"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.i686-w64-mingw32-cxx11.tar.gz"
[[protoc]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "488fe293ca1e324ce43e7a5d8034ee2cf23ddeb1"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "c03b79ac7bff3e300ea1aceac37e83428db4611b3c806d50087fcc15fe80e90b"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2fb041c2e44c03d4d327c29c32c3d3dfb043fcd"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "1b9db51a513411739614c6e538fad1262a426b92d45e4b19fa1949641e800f38"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "f6558f4508365b6a03b5078ebe3c271f6a0b35b6"
os = "macos"

    [[protoc.download]]
    sha256 = "41a920524957eb05301fa0aafebc82b62b7cac37c085444729febb93f52bbcfa"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.x86_64-apple-darwin.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "677930f33251136346598c5ce3f344735cbae664"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "45585431fc02e99fe80db25a9ede4f7f6b9c4bf00291ff32b60bdd17493217a5"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.x86_64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c4b745a8e6f9478ffc074bb9ead269b343495c4"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "0434c848fb3b35ad19e244a8d68f88526c61039de54553675e35e45b1d99c36d"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.x86_64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2468b69ea96e8d8d62b6f63f920622d575a2876c"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "19d524c800918d97589f3436aaeab02d5768e0dbae5c0f6c4c35fb8429dfae48"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.x86_64-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c53a5196768bda02b48ef95cd9ccfa360a75dfb8"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "db8821794d911c30080feaf9f3abe41151a35e427df2831c8199d8fa9dab518f"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.x86_64-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "ba2b97ba461f9616c8780397efe0384dda3dcbf5"
os = "freebsd"

    [[protoc.download]]
    sha256 = "27ee3e705ce02e94cc595ed6828b96fe3110f820eaef21517e35c92cd400fb40"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.x86_64-unknown-freebsd.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94fa5f2442f8167d79e6a14e140f9bb8b275a5ed"
os = "windows"

    [[protoc.download]]
    sha256 = "ca6ea9755fa2a882b1d39de071c1745f20c89cf14c096ca6062db8b570f8a350"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53edcdd11264bb05c07d91ef79520289e52f845a"
os = "windows"

    [[protoc.download]]
    sha256 = "0c338fe508f9229ed1c06e0e466a86fd4688e62f30a914d39238375b8a49639b"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.19.4+0/protoc.v3.19.4.x86_64-w64-mingw32-cxx11.tar.gz"
