[[protoc]]
arch = "aarch64"
git-tree-sha1 = "e0100aba5e1a1e17ba3e5162af1a23b2e66ac4a0"
os = "macos"

    [[protoc.download]]
    sha256 = "967103f8ed5f73cdd83bc516add059dc09839db9d3d58f14f1ef45031eb48058"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.aarch64-apple-darwin.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bce8cdf8d74ff9d4c4e3a183803605b9736a8e1"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "10123dca50913fbde9b7a43232c710ac63e94b8cec1b4650059e72e23c7eae2f"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.aarch64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35df747eef6ebb59d7ab82dcba6d6c35f2342265"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "964ce801a6cc5e54cc5275f278015b9ea802a062640760fd496233739beb7f2f"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.aarch64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74bcaa068d316b616d839d45d46edffbd2b6f743"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "a063e6da349ed9dd8b1ff42e37baa967a726ff4c4064297c002087b7c0d88b39"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.aarch64-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "187653222925ea8dc3064a804781798184e805dd"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "852bce347e879078562eefb723610780cf9ec43b2369f881175f8c018c530481"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.aarch64-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5067e994801240b618a5829903a743ae398655d"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "b83e795d51076fe4ae4fa56f582f357b143fbfd400b22d60070c4522fb97fb40"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc7da38c9a7f4868681624f118099efea478806c"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "54446b90ff237c91b09b0566575a429f196d00e30193753f6e87c4e015946bf1"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6fa92294b8b95e1f74129f56e345e95e6c358c8"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "ab93a9f001327b9b4caf65d1fd7246dfeb414d2fc695b543e4ef7e5ce34b20e2"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.armv6l-linux-musleabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e624c65c15af83fec1603783054d3e674edf9603"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "75fa22cd5acfd2f6320efaca4053ad4b95f7d5fc56a9e071161a852ba8343dca"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.armv6l-linux-musleabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de1e41fc9eb1d1e147bad26c2e3478d8f5daab8c"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "7c83b8835b002387561b7f077a2fdfa8338c2c018b5b9cf6c8126191da276d8b"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0eff646619f6c0c415411936eb5dd55ed57bb948"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "de9dc0e15351e8d23d75c523fda16c582169549cf9392db0fcadd45325ab8bd6"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc44d866ad92935e9f265e0d39bbfc100d7e7f8b"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "106f545d72e39924af69c03bd2a873b415a004fb7d3919695dcc322a4cc50cce"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.armv7l-linux-musleabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a96944bfbb21c5db873b2078c5f48ed5bd83f9f1"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "3774ca80f7a5ab4b517cc9d52d64edf37deda4d82daaf4d40ae64694dbdfe3b7"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.armv7l-linux-musleabihf-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55eb3fad2c03d62cd8728843dc3a119ce837fece"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "403ee4aad815d172ad907649e1f82aa0b3a6d838022a5ae190e26c74211e3748"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.i686-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4c0e7699e594ba049afd086e9ac7f3a05db2550"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "4658cac30d64ab926f810f14da0d97af6ecba9f49e0ee982f1a50a83b9564682"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.i686-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bbf4acb8913a29d79c16bda72ec41dad454168a6"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "c5755fdf6e95f22648fa0453d470517c6431e22f371ea459d5bb56a70d03b6e5"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.i686-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f4293fd6a55fac5fbad367eb1be6cd706f97089"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "a9660e0fcea31b3afa0370f5ff8d8b7b92f823bba5034bbff5ee01f311965266"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.i686-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd05e8dc4586f5879ffb457becb4678ad07d1a6e"
os = "windows"

    [[protoc.download]]
    sha256 = "a2b41e72f16e39a11c3e31c6aad76874fb02fe50b58dda8572df02a600d85e3a"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.i686-w64-mingw32-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48e866b23d1b8e6a9496a1fa68df01a5f754da46"
os = "windows"

    [[protoc.download]]
    sha256 = "6219e2f13ebd2e99c19a557c6cb430e9946b07f4736b98db54309855ee94464e"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.i686-w64-mingw32-cxx11.tar.gz"
[[protoc]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69cb325b71d3f353768434e506c5979b8db476d2"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "ab02dfe2077c2c24dcb74ea68b1af615de8505f4dccfa5abf1e1ba9f418b83b7"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.powerpc64le-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "883cab1f6fb9669ff174422ebc76b84d33d120fe"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "3d8b2ce78475e3b5311571878257794eb0b5ab7e0e99c06325bd48eed3eb9973"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.powerpc64le-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "3a381f3f59732da8021eb9501131c5a865dd08f4"
os = "macos"

    [[protoc.download]]
    sha256 = "afa8be9d5e9fb1b2a662fe3ec1fb45285b9b7c54a0e3d217b15b9ba4d8a62ee7"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.x86_64-apple-darwin.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f804f22c21436bab23642f051e23281d16ee4e25"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "1b94ef150323bb1b223bf30b8af05cd56d3c82a6f4c8a21c6c5697dbe3d94c66"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.x86_64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08d6d408e7ef4ff1662f8bc8b78fb3082833acfc"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "73dcc0bfebee8b04ca34879812e853777f747e128967b5984b8946a9e248c88b"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.x86_64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7513fe63e8b019503728757eb5d692769f78f1d5"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "40f79d0a95e537a7265012e69f0a84d01e63cda24e34fe2f037ccf128cf0d332"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.x86_64-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11f2d727d78c29d1da7651c8b02b90739126dbc4"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "f1d639790986a3b704cb6a50a694cc7b78dd4561d13dc3b117466f639b413c6b"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.x86_64-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "3727231b6f3f76a54fbb4f3cd50f37cf00d2ea90"
os = "freebsd"

    [[protoc.download]]
    sha256 = "3f919f2b8aaa87d0cb1fbd28b209b1f713a3dfdab73f6d46773339414ebe5014"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.x86_64-unknown-freebsd.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd9800dc07e1f6961025534058f4d212da58dfd9"
os = "windows"

    [[protoc.download]]
    sha256 = "0e8d80e510cb213ecf6ac73aad3a33b4ec20810c88315b1562906b533c7262fa"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.x86_64-w64-mingw32-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "317140672b46e8087ef7b060971bfa300b682a23"
os = "windows"

    [[protoc.download]]
    sha256 = "1d5ca77cb0dfa0b98e99ef6c526ff7c02beff0cfc4fb16237b4cb2cffd6153cd"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.12+1/protoc.v3.21.12.x86_64-w64-mingw32-cxx11.tar.gz"
