[[protoc]]
arch = "aarch64"
git-tree-sha1 = "c1e02dfdc7f609227c56df50b6dc7f8c3a9e8fee"
os = "macos"

    [[protoc.download]]
    sha256 = "031db39754b7ad0c5ff71c929133658816b786f41055536e72dc8c34766c43e0"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.aarch64-apple-darwin.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a290ac4823ac584ec1acdf4f2875a7432776887"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "e16628f1415d12fd2d8a68911c5a534982543a90daff742312039b652019a1a4"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.aarch64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "966fd87f7b189a0a385f434a3d517d4d81c393fb"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "e4966c06e12ec786af6b09961511b98376657c7868ea218ff34777ee00826592"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.aarch64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c435613936559329bb981887210f7a800dd18ad"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "b3f7b4d20539fd093a696d78364e259478542d33180741cb26707b56f41a4531"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.aarch64-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fc6d483405aa62f3044bcf6a8c6902f0d7aa4fb"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "9bb1f92dbc87ebdf9a836d376b1f44b71c3f44fda96fbc59cc2a64e53b26cbf6"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.aarch64-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "aarch64"
git-tree-sha1 = "b7535da529c31541b1dadb50179460d9fa6c2828"
os = "freebsd"

    [[protoc.download]]
    sha256 = "b82b9a87709f355233e862072cf7e3263080b5785b72928fcf35d19ac3e55780"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.aarch64-unknown-freebsd.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a594f96d1322bb6eebd3f16e230ad8b4a28d99c"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "3857a736240d1d34f2d128af1081ebf7d7f9929a3c855efbbff9b0d6888cb5ec"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0a9ed079e4ccdf5edffa0035b257a94182a551c"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "4bce3a7ae386a78321d9d3765eba6514c47adb157b24a4fad04dca929a4a4fbc"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f370a271af6a85d1beb6effd0070fa1cf89fb9f3"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "59defd5a8aa846ddff7ec64468b652388a0b56112dbffc97632c6b1b41515ae2"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "902f84e2c76587f9d2d699c23902f5bfa72ad2f2"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "c9e6cd191afb6b61c9ccc97aec0a7d832fca5eb78ecb378f3c994c571179d611"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6c6b0cb069b21f2d62b2cba0fb8515954a14dbd"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "72e67a780de458dba3da92edf2487e4580bb5974e1b1cd1d1a58b87e916a7714"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e5fef785e98f9dd7f60fd54a761817b0e3e2ded"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "e70ad07ba380be80c8355d12e0a07906d7d16b5f204c93a1b908498723c7a8f5"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "816fd3e2a792ba91ae9aa31d0fda361a2d2ed7da"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "282d2be3acfb6551fdbf35d8663c5b47d221683ada687a9eb42057a25c3c1a28"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a761d5ac3a57c5ae24ca07bd19739ab895b43f01"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "5b295b40bb5580eab56425989d7525f87c998543c8eb3019feba53670c6c721a"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "010278c8406dd58286f41ff5228779ccd42a370d"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "740e86413c849d280a53f21f50ab529525b85a7261fc644fa3ddbba13d8cc0f4"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.i686-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c5ea0b1dce943ab7d3ef5cd2e8c2dbdb8b0a969"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "2eaf83fe939d3a7e0eab0562abdaf274bc7496f283a222d913598995bc9dbbb6"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.i686-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd91a083b00f5860ab575398c944dbba3f157b01"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "12c946db7b82eb4694616ccc969cb3e36b3b1a219feaf95688c455a69a3c5541"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.i686-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c36c6181bbaccfd185602884fd8113c90185c8e5"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "da2a6a7f37cde0b8a8af958b4c7018a0a9fe4e737ec61faa6594abb9d04e1a5c"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.i686-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49b8e902c584eaa43fb76e3925d5a9f2755330bf"
os = "windows"

    [[protoc.download]]
    sha256 = "60c1abc434bb1d0d20bcba99b67357d6e5ca332259cea5c6bccec3f065043481"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.i686-w64-mingw32-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7efd3ae2374541bf52b0c2e33b9134aa1717d9eb"
os = "windows"

    [[protoc.download]]
    sha256 = "8488432edd53a7bb1129e6d7e7f59c35ac5dc6c036db7768d34cd855e62b083c"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.i686-w64-mingw32-cxx11.tar.gz"
[[protoc]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9792522713aee44cc9dfe2340550ce16244299f2"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "1846c50dc0565feec08f7fa201bf33456a94d09b640e6fe5182103b0c5dc2282"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3cf6bf4cc2bf8ca15379b4c6fb55fba6ebdd572"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "41ca1bae5eb0e7b24e72c65d9b80b6f48cff30d9a4e3fbd2127f6f9ebf444a19"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6206b43224621621c28ba8072e3968c2cf665918"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "4704754455e537e1aef3cfca9dc7f07216fd0f2c2d682a3d7e795bf9e8bc8a7c"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.riscv64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d98393c8cdafebb6610861a8bbaa1bbfcb8d513c"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "d87136716c0adfb9277dc9f8168f55f7d5d45d5031249e932d5b6432f45c5acc"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.riscv64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "79b6cc972c92b050175f337670ff9c3a057e2b1f"
os = "macos"

    [[protoc.download]]
    sha256 = "53b438418f0081ea889a54da62b5efa71e76efcccafb90eb4d61cc8e2ebd7de8"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.x86_64-apple-darwin.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb28bc8e5483a4afbf513aae2c004aa020ba89ba"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "a839d16fbc6ec638f4ff627451b1dce907063a5b63c22d7feeba2638e56bc7e0"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.x86_64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3256ac98b9df538966a7cd30f40e42482ff46ada"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "88002466c83de9bf2192b55da1a85e36d4d45040477cf7f2bf7c24cebaa1a211"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.x86_64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "867253faa8144bbe7599a69dfc0e0ee245472f3f"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "6cba7a48af5ccb486aadbb77bdfbf11fd402f35c712d46e2b1cfc4afe6f152de"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.x86_64-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31a4eaa061c5d4824392b6bff9778a5a9f76a764"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "584a41790c68356664a14ffd591017b602bb71892d252f12e0aa5125fb96e03d"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.x86_64-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "07f8b24eead83168fff488c6855af01200e29265"
os = "freebsd"

    [[protoc.download]]
    sha256 = "43c000cd3b585f5cc5e8f6a08ff264cd597667c6dfe0f3f387cbecf19d3ef798"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.x86_64-unknown-freebsd.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15cfca71c428261cf27bef5261810df5d028b259"
os = "windows"

    [[protoc.download]]
    sha256 = "5bab3c0ffc11ef2b29ce334f9c077e115d7f81debea5b93740ec55a207de59ec"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d9b813036d22f5002d5488b64da3ad55d0171fc"
os = "windows"

    [[protoc.download]]
    sha256 = "46051316811a8c586ca49c7881ab2b799b412fd22d0bc599626ef453409778ec"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.29.3+0/protoc.v105.29.3.x86_64-w64-mingw32-cxx11.tar.gz"
