[[protoc]]
arch = "aarch64"
git-tree-sha1 = "d87140c13f44999a7d5f4dd30eb9aa087496cc67"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "dc2c388a13df1304a23a6c0bba8411d73afd22ce1039836a96e9d1aa1f25053a"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.15.6+0/protoc.v3.15.6.aarch64-linux-gnu.tar.gz"
[[protoc]]
arch = "aarch64"
git-tree-sha1 = "8821cf9dbf30d5b872c39866ba1060151a6aeeb8"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "d74326188c3387348ddd1006b2bc883eaf04fcb80a568f4ee98f621683fbeac9"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.15.6+0/protoc.v3.15.6.aarch64-linux-musl.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0a02a9d895e9dc4f41f6701d27567809f4c6c88e"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "c6c829c16eab8ba0741ba18ef38e3f59f6015983b53d8edf4a53bf086818c571"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.15.6+0/protoc.v3.15.6.armv7l-linux-gnueabihf.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e9a710edb027e46e5ca3072de2e38dbdf6fcab12"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "ac387dfdf60c768d8b50edf480b7ca07aac1386d6988a0387ac0a8931c0d7d20"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.15.6+0/protoc.v3.15.6.armv7l-linux-musleabihf.tar.gz"
[[protoc]]
arch = "i686"
git-tree-sha1 = "999412b99443bd04ddd3ca0d6843de0361e25453"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "580a98d4751586216aced6240d57ed58d93910d3e71472042d29d3cbf1a07557"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.15.6+0/protoc.v3.15.6.i686-linux-gnu.tar.gz"
[[protoc]]
arch = "i686"
git-tree-sha1 = "9fd7054619c0bd04dfb162c786c1cb1ea14f3f01"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "363db562579ab68cd5d2bf9de71e740e8033fe9aedc53e392d30cdacd660200c"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.15.6+0/protoc.v3.15.6.i686-linux-musl.tar.gz"
[[protoc]]
arch = "i686"
git-tree-sha1 = "6b10b6f8ca31d772002d353e39a41efedf721d09"
os = "windows"

    [[protoc.download]]
    sha256 = "370cf388e55b12a1decc8f156819229ad5e46c0678d066f43f0d26618829785a"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.15.6+0/protoc.v3.15.6.i686-w64-mingw32.tar.gz"
[[protoc]]
arch = "powerpc64le"
git-tree-sha1 = "2a6ee8c7b7d092a41617915b99f981a603779d89"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "17f989c04aea4052ad9d13329f83c5705ab15de263df9d6d040356c5d22156b9"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.15.6+0/protoc.v3.15.6.powerpc64le-linux-gnu.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "82941d01d8db0fb1cac4f0a5cdc2681b86c1b1ad"
os = "macos"

    [[protoc.download]]
    sha256 = "780872fdbe91a4485d55f581e5c041aa3c83645b930bff2b5a3a9edfa75cb11e"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.15.6+0/protoc.v3.15.6.x86_64-apple-darwin.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "5da4acd6fa127f57405b1b43573491309d0aec15"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "54b7f75d1e908607a930bdf8f6f12f6e5b01b5f6d21c293e624e9471cd402f87"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.15.6+0/protoc.v3.15.6.x86_64-linux-gnu.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "bc90acd66359c000f79ae28f54114aae7ee2978b"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "490d0dff56b10ed99ca058606711d10ca7d8f2d54e57c4ed3e6bbc0a637b46b5"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.15.6+0/protoc.v3.15.6.x86_64-linux-musl.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "0dbb8cf2679d4eea26a7202f580f9e4a1bd6477a"
os = "freebsd"

    [[protoc.download]]
    sha256 = "b93eb7e4e409d9257ecf1aac9ce380264d30df3076fa02d430f5d213891e154c"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.15.6+0/protoc.v3.15.6.x86_64-unknown-freebsd.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "51687438ed08ae061b2b96f18d0b569df3201a0e"
os = "windows"

    [[protoc.download]]
    sha256 = "8c50cd2d342e02a5799794bdfe13dc2dff4a124edf257cd898c556891f59bb07"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.15.6+0/protoc.v3.15.6.x86_64-w64-mingw32.tar.gz"
