[[protoc]]
arch = "aarch64"
git-tree-sha1 = "957915f4ba94d688a011ba016254d8ef74ea33f5"
os = "macos"

    [[protoc.download]]
    sha256 = "783c9e7f45a92ad053dad1251531694fa3d3fd29a154b012ee6e8b44483616e9"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.aarch64-apple-darwin.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9df64df533f6397367536d95676295621d06d7d1"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "8884ca7d42922ef953dba9bd350dfd9cbb8c7e70356d3d9fb978493ec3912206"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.aarch64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bbe903f51066e3930c9a2c6a456c4964995798c"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "537cb4148530faf1f45dbb370719cdafed2a551a03be1fc799c9a1ba8093c5d3"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.aarch64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7106985f66351b18f911b39b653ce23377df3e1"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "bdcaecce39ffed89e7a8d8b642f7022614295f6f555a39aa171b5b05c651cad0"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.aarch64-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6878f1a6ed45632f018736deb70ac0b01320574c"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "a84c521ebd6fee9659db35b68698edf34f1344ae5b2db902e7adfb59698576c3"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.aarch64-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f357464bf679cb9de390b502fa91d96b4325a973"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "5e745dd7847234ca747312d70799f8edc19038984f0246ab09a2259486fc9c7b"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "920dcd06f43e1bc528921dd45050f6d6a0c859fc"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "f922417197af145c998d65164b661494dd910cbd2a96f6fd034fc938e2d6c21c"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c1d85f482ec1ac9c464b1f41b48d6157c165fb6"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "9f8d648f6a3efcb7cbbf8503d64240c1565e6c0ce752da73d55f6b5f15588af6"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.armv6l-linux-musleabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7abbaad195f36cb6d868c8477820038ecde303d"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "876f01f37df390406c8d39bb8bb3404d6a329613599608d92301fca57644ddec"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea420e92343cc2e1f5d893beb1bb318ab8780d2b"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "f5f5af6ed0b0c636057110453b8312fd936e9f59820f9a90c3678b785be2e48a"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "606fe1b219c7cd321d7c4582f7d8b0233e770d9a"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "9d8e5c407a110a0470b7f54d9cc5b56637b8a6774ebfbe5a4f05d278faf4d5df"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6653f4efd00225861d3e078eee20d918cbbd3c88"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "a2847a82ff0ba0654825ddc7832f86f412093aff27b6f4e3660a2300665c9c4a"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ea042979ba256545fb69084b6339faa33f8197d"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "4dd07abd64e1c75db14b11e1d99f7fa12bc6ce7802cbcac7ad4bf1100a416a1c"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f87febd696d319f925e02b992ef678c972645f0f"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "d652a8d5a32875c027f04bfa443ca5344f9b3dff5e9ac57128132c30964dd1a7"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.i686-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afebb59a4c8f104f805d39994d0774ff64bf417b"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "f254ffe47dbecaaf21dfce86e35d6e7b10c82dde30699f4d7407d231a077a7c7"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.i686-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1843719693eafc2e44e7a589ad3fe8e19a07a21f"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "3f875053360757dfecc601ce46bc29c16f909b54108938a02823f3fc44db4ec6"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.i686-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83fcff46a7519e5c73e0212998576a5a703aeeaf"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "22e23425b538804d7bcab2523d7a6d8c5715586e30b11444ddd7862de9876034"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.i686-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9751b1c4d2f8c0d4e73930ea7eb8066bee2743e4"
os = "windows"

    [[protoc.download]]
    sha256 = "ac3f32c2ad13e92cf8caea395399320dd0e8aa470649f0546855c9f1e7e1c75b"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.i686-w64-mingw32-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db63f0d7ce1d6477336e62cb474db0078a20e67e"
os = "windows"

    [[protoc.download]]
    sha256 = "890a72e686176b26bbdf3a3f05804bbd36e32a9792686244bf0bb69cd8367c9c"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.i686-w64-mingw32-cxx11.tar.gz"
[[protoc]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "333b26f33b7d20b57b317c8f31ea9a788e558285"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "5456f8101200d4274698343ae555efecacba73ec23b7e6d4562f371c5f1f7b18"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7db07df41cb12c2f52497776017d134e2b8b01ce"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "afbe995196c7bcbb364ec773920e5362bfa10c1a8212365ee37f20569523d59f"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "601cffa263a129e6df2945b0e1bc861ab409d7a9"
os = "macos"

    [[protoc.download]]
    sha256 = "b8092ec8c786aff451876f543ec77139a7b128d13be64f20517cb3cb44667da8"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.x86_64-apple-darwin.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39699011848e620f09cc9a430fe132b49d00cd6b"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "3af63540a3eb958989e3aac7861a6a7e3bdded092ed5d43030db900d644330c9"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.x86_64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d25fc3df33d9927c00cc027fd99cd7f2c66b1dc"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "3446d58c1112e65acdb199f80b92f5368137378a537b7e4d4fe3e897b5001559"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.x86_64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "050953d28edce9cdc22fcc02dcaa61b6cb9424dd"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "77c07f784d493eae25298d364f210e4beb035a15e96f5c5b5a2de5e6249e96cf"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.x86_64-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7a19c0e5bf1e65cfc57fea0655089114f33cf94"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "395d23396c6e266039278b277f2990e04c083e6cdc52b7a23eeadd0d00349fbe"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.x86_64-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "6f1180434de1e5d3cf5c437acdd3eb511eb002e2"
os = "freebsd"

    [[protoc.download]]
    sha256 = "9a2271e080c2a5d3df7b70fb8dad4cd242984b7027f22239ba2eda645a212d7b"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.x86_64-unknown-freebsd.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a62ecce570857eba22a8b6b42412ccaf7626610"
os = "windows"

    [[protoc.download]]
    sha256 = "40636a04bbd48ddb6a905d8a5091c23d5a242e4d4fc2b3968c5192d6ecb0a399"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45efa76e04c725688bbc70d086e58cf0903672af"
os = "windows"

    [[protoc.download]]
    sha256 = "68cdfeb62e1addde094ef08f2a195779e72c1e4adb5c2e20620eb5f3b66193a2"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.21.4+0/protoc.v3.21.4.x86_64-w64-mingw32-cxx11.tar.gz"
