[[protoc]]
arch = "aarch64"
git-tree-sha1 = "15ba83f86877d6ce34f93cbf306a9b1dcab1724f"
os = "macos"

    [[protoc.download]]
    sha256 = "3d5e71eba3763c4b940994527bffee15b319fe6aa2c88f0e3b4af829a2b3537b"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.aarch64-apple-darwin.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7910f3138262dff8a9f96eb2fd226e91936cbba"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "725c2e20a170628d37adb8196fa251bcea3f660dcfb0fcd787e3c8de3120d954"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.aarch64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a908d5ec21658e434699d1ad49b223afdab021f"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "6e79e462fe9f5e4b3e1aaf8db9b92ccb5f41323d5e137b71381c03d1a0baab0d"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.aarch64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "761f319e03df7ea73f546e0bc11c665ba0ea4451"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "d8731a7a75da6d7b316f8b8a466d31a1386be481e85573a7adb5c3121db74f31"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.aarch64-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "166e1487d202b52aeb3ec37ff5592712271d2e92"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "dfe7f54aeb0d2efd9b64a34d8858190e2122fd2d62d587274237d7ab44efd85b"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.aarch64-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "aarch64"
git-tree-sha1 = "1fb2ec04f97ca34f5e4215d2b02585de35fbf7a4"
os = "freebsd"

    [[protoc.download]]
    sha256 = "f45c69422e565db641e612caa76f2e833b408a3f7265864b7a7d888a8e5145bb"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.aarch64-unknown-freebsd.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa35cc48b3f99a45188f8b399bbbbdf2673a17d6"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "0bdbd28e696dc7bc59d02393ad1a032ab5acd2ef5fac7a968e2f432b3324f213"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3f0e5ffe04e5dc35d0eca7ca73a573e25b9fb24"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "7cea3f462aad9306fb23895306ecd06a1d05b8d8de614a2d1759ba231a09dd07"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "681799978a5782a840aca27eed8acdb403613785"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "6a2d50de0203ec145040a04bca71d03b5280bcebaf291f6e1c73ad90afb17d18"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6018a6b289de02c9302e8385288cf4f27ffaba1"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "fd46f0f14b3c6cdacf18d12f849dd66364acdf09b94aa2acdef94cd89e274f0a"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5343e780d3cd525fe6caa2ef7b24ae5218c566dc"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "64e2f8fee7b3b84ff74f269fc966595c8eb3a907db14ce69a7687795fd476ada"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "888d48bd8e9b7c3b23774d883931d6b23022029d"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "7374f4fa8f8f42f50af846acb28f372fa89b94fe7f50857f0662fe50ea6a5749"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f64d9f6c6059ed2b3a5308ef55be6aaa4255c12"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "06bb6a5d5ecf3e149ef9f8865c70bfa74fd18fcc0d28a120c7fb5571ae830687"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f01178cc3f93a121c28e7a6ccb431652b25fcb2a"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "7798b0eb41a893baf2075aa5f66b506c6abf7490c56f905d63c2a72c9c3a66f4"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87ec78afdc6e5df2ced9e165b806baab73341b62"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "f0212deac101d6d9f31be5335e90043d0b97df4b5063f5d72f51f1f1056ff712"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.i686-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de746b808eb69100a2b41f575dba4a87ec6b05bf"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "7b9affaad073bc974c7837180abad29dbcbdcd2e2ac9e6c5586f8d8d31bcc763"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.i686-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4626c5f875b6867b37bbdf0236c70506b5ca3a06"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "9f269080696cdd6628f4e4d4ea97bf995eed3eed8c2aee3b3c3961f9b50f99e1"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.i686-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71a512c11c7744f95767cf811c440491406e57c2"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "710d8940f143baf01fd509f3bff45e7588c4ff006d6fec90e85d9aff6d92239e"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.i686-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff2a1434fed784afb6dc4e286cb79fe6d46bc87d"
os = "windows"

    [[protoc.download]]
    sha256 = "2b5ea956c5eaafbefa26d42bd911bcc46b5265e2bfa697040ccecc297214e358"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.i686-w64-mingw32-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62afa53c7e0610d3371ae7d3526061bbda58a62b"
os = "windows"

    [[protoc.download]]
    sha256 = "f3066e1728dc7e22b538e8d746a5d7142f7b741e8ecfff112244cdadd0d50295"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.i686-w64-mingw32-cxx11.tar.gz"
[[protoc]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80fb1dae7dd1f70181ae256d4ee6b15769ddb092"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "57ddd823556f4c5befd092858ca4d0e40138a2efd29500edc836f7a4896e8674"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ccf23a97bbf61e346352e35e09c7647415b50a5c"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "f420cf0301c7c94f0bf122ba50a7e3cea44c28848f03b29206443966313af250"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "9b732137c29350788ca5fc5658e18eab4969a63c"
os = "macos"

    [[protoc.download]]
    sha256 = "8be4e89e7217ed76a4f1366a1a2f39ef85ba9a98fca5a4f3db3f3179e5017f4d"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.x86_64-apple-darwin.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce3165efc18fbc7dca2c0dc06b3a8b1301d94d40"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "ae73de8e5cbe582e04f1a975bc4f540e3a37652244e7754fd443a4cc4d97b503"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.x86_64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00637cf715fbaeca12257a78412565105919b028"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "ffd5db792f42ee60e5b662f80a8582ff15700d37d7c7ad235af73483a67a783f"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.x86_64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f10b2e5c406e6a4398de74607f1b8b60188ae6f"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "ab041fc685421de422f6a290609b108f23e9dfd53b513387ca5d9db5e52e47de"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.x86_64-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aba1db3805854018a5ae6f8a063a48b7bfdb0eb5"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "82f06d73aeb39cd9825a7e584ad577fc1da0b95f7c29472913961a05a73477f1"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.x86_64-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "8e3b267f11d66c67f1bad2eb92c750153f6fbd93"
os = "freebsd"

    [[protoc.download]]
    sha256 = "6dbd865989ba1caae465077adc45a489951b7923d8de2a1d011b8dd9500fe7c7"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.x86_64-unknown-freebsd.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3aed18d9b1672ba7517680b3f6b7cdd63bee92c"
os = "windows"

    [[protoc.download]]
    sha256 = "0b5925c8ad7672b02f601ac79ba0c3eb8dcb0f71426ca3f285c2e5ead97545a4"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34ba71a0c1e6f2ad04a2dc057b7bdb5bf5790895"
os = "windows"

    [[protoc.download]]
    sha256 = "344d98a331ff8790eaab1e18cea39400902d0ff437dd189d3c40ccea6daac620"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v105.28.2+0/protoc.v105.28.2.x86_64-w64-mingw32-cxx11.tar.gz"
