[[protoc]]
arch = "aarch64"
git-tree-sha1 = "e9599fdbd3ed64c54dca90d15d0034d00ba38fb8"
os = "macos"

    [[protoc.download]]
    sha256 = "bd9175087bbca98d0a67c790fe16c0b63a0d393188028af95c610f5e63c0386c"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.aarch64-apple-darwin.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7d549568705983ee99f7b4d838b2fd7b9034a1c"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "b22a3c00b3354ae6ce94f022d4221a0c7261c6154ac04a85cb24e40eb59bf856"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.aarch64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a8540e2974a2098599a72f07ca19be531072025"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "e0b7719976c628e361899eeb8e18f3e6c53f6842349f9da9aefbc7cbe004379d"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.aarch64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "093b882fca52dba0be1246e34af1c8718727fcc8"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "76ab08608a31327110157e504dabcc80d8cc413fe2d8837faa9a752be4d8a632"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.aarch64-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a412382e884d89615c6b829b9c10e037c5de6c0e"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "019ed7f838585b2a0bac6be310b553ead5d14e42ccbabe0fab0a633d4fd7262a"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.aarch64-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aaad9d3779161ec11d5fd136f0661aa2cb6496c7"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "7fe8dd85a063ecfe1529e7024524c33f9bbc99b5923a23f5995163b219554b4a"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7235ef353d2913e7fce2073a25129562231b317"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "8c6bb7aa0832c4a7357d3e4163f418cc8e724820b97e52b2dd390eea8e9357b0"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7d2f8c3a1382da41f738ceac8ef4283c23e3c45"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "0194c691885d504b2ee35a86c8b2f3b37831250b88dbe2a560a3bc2e5068754a"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e81654c381ba8c0b866dc6b9a76c2321d4adf944"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "25bcdf215ef729a09d51fd819a3c3e120d391dad7f0fe44e5c0399db58d15b87"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab388bd6611dafd1a7edaba5a5cd803b72732b8f"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "25be8422991db9a51521acfe3e002dd5076ae3d23b754f297558cbfe94d14db4"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a9eb329cda96df7eddc1d21d1862db92768b039"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "1e55cceacad9e6f60e69346dc47badbd91bb2842991b151ce44ccb73334c6a70"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c15c27ac2e642f98d43669b2004492847c99f70c"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "9bb96934e5f5f92007cc89a322c3e78f26b4fb7c90127147f1167e931f6ab260"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5011d4972cde5c409dadb6228b167f1de35ed2a5"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "19ec9558ca9e8c3c7c5eefa26ad3ddfe5a75eaeaf2396b09c5f68d34c1cb70ca"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13e7832a05a0e2043a6948958816636a8e44fb25"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "f03c2bf4dd61bd6b9a61ab59f884d2dfad7c27af7ce5127e312db47e2ca61bde"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.i686-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0646361272c3bdc453eadd90bd238058b9ec3cbb"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "da6e6a01b4689172875f3f429c60086639be53272c80ffefcff15f65ed8cf568"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.i686-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9faa386129a36b901f07b7c97a788db2ff854d5b"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "b4e6ac01c3329d38dc3d5234e4c66ee4417d8c0564aa2ce5e262d1583f0c400d"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.i686-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09cc8f98c6fca10b70bccc4e2d0812c397e08c12"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "783098f051d91b3e44726c7b6ab82ab72b945ed6d1447e8cb8b6ee98e424b7cf"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.i686-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fb683fde3972f2cedfdbe58c5a8880be4d95539"
os = "windows"

    [[protoc.download]]
    sha256 = "429f3bb3945059a3a00e171b353c34567ee5dc21f4088599af5af1749ff52483"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.i686-w64-mingw32-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd7c6751b222aeeb9dcb5bdd5ed7cc21fd5f277e"
os = "windows"

    [[protoc.download]]
    sha256 = "d1cd5828fe1f40c537e623b504f0645f23547cee451cc5d421e60afaa5c9b48a"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.i686-w64-mingw32-cxx11.tar.gz"
[[protoc]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b710bf7b19b603cd9183c94633c2c2c48d07b074"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "a123b0b3b979ba8821324a4f4b1d89bfc7181b51ba080665bd058eab4dc71791"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f2f8d5060f0b5aea4ceff97e5e49e1f58c5fb41"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "82f01f485f03c1e9a68c402498b68606198b2e4e2d8c922f94ff5eb6c48730d1"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "44ac5db1e93149437d95750800b15c6fcfb7627b"
os = "macos"

    [[protoc.download]]
    sha256 = "99422c69a6a78fcb5e4a7a7ca7580293fc52bbe923652876b31d5ec9f0475a9a"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.x86_64-apple-darwin.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8d9a8079bdaaa8ddc3909aff7a7aa6fa89f9bb4"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "03f2b1e6229bcc93d807947a8e674929ddaa75965012a9834e6a6544683f798c"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.x86_64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e08f4e01f63841db08a98edc7c527166714ed2a"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "3d39ef9eb79ddfb5cfb75654e770200e7e91b7495a4eaa4e0fc5957f4bfa4755"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.x86_64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5fd2cde6b7a338806fd7e78e8687642dfb14fc14"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "f9bf94b892d8610641611e7cbc24b97fe4ca305388da95e8b58d0f35506087fd"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.x86_64-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55e040c8a90cd754cf8545e36986f4c017d6deee"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "b45eb5f6f2ad021b706a277df28ad60907ada1e6b66e3be8469e190bdddc5659"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.x86_64-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "b9e419916fc56322559987bde1c16ca8f003098b"
os = "freebsd"

    [[protoc.download]]
    sha256 = "6a96e3bfe9be3edaff0eb4d26b29a048fc872b3080dc6ad7c9d7813d16b9f165"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.x86_64-unknown-freebsd.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a18e5f962e2cc2a2d7066283225f2fd4f576b562"
os = "windows"

    [[protoc.download]]
    sha256 = "65a60c03e824993341344d7bda6c25f05b2071810a39ee8dcb08bcf79b72783a"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79bec9bba37dcdfd69ace3dd68090fd98386d742"
os = "windows"

    [[protoc.download]]
    sha256 = "7bb1af33e142c1078f6c973d8552f2f4b4171c17a9955b380fa2337339fbe92b"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.16.1+0/protoc.v3.16.1.x86_64-w64-mingw32-cxx11.tar.gz"
