[[protoc]]
arch = "aarch64"
git-tree-sha1 = "18d307595f78519ce1ca29041066cc72969f17b9"
os = "macos"

    [[protoc.download]]
    sha256 = "c78b83cc1f9156a448a5fe385088ff705ff2f72e81908a06e848346c95e870b4"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.aarch64-apple-darwin.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19af4a7b396bb675db5c897ff93763e2a09f5077"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "4fb3375d01182af6f5fd8f470d2818c5296fe4862a53fb7145689090d7b5d2f9"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.aarch64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ce9f86aebe89ccc131e3210e017053eb638bdfd"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "3428cc51a55e525da096fabe872df14fd4f2b46c64dbecf1df1dc3b90f244a0d"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.aarch64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff6fc394db02978caad06a2f9c609740456bce7f"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "3c48040fa8e06c2f8106c6219869100928ece9b19d00481c43923fdd5f9920c6"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.aarch64-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e405255440a8ceb9be3108242dea92e0624bdbc"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "d6abd19603909d4c9168f7ebc1df927f489febb5856b1800f9abd54d9c832e08"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.aarch64-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0be607a893ef79cacbaaeb6790555baad328f8a6"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "7316b9679b1bb12aa94512763db5d9296165d62dfbc13f999e6c8ba693b5cc6b"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0bcf398f7702a50ccf3c4971be1c914ec7a099f1"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "5e93b7119a88c6d5ba8dde42866e0ef624b8e4b53cdf637cbb97abf18e0150c4"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "662af40d54b5e883b92f8b67c2e8a93c456626ad"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "132912f1dc825837f78a48be1d89c1a41d9d355cf16e53c074e95c7efeeb85ae"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "800f21b96f34bd151df1c55d41f344bb473bd0d0"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "6166cf4e81b20a365129dcd24932b8cfef3be248791212a51884548e9450120d"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f838d686b20ebc3580c6559af94328b900ae3a6"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "c0dd9513a690e080c49f128ecc65517fc7d6cc191510c2e2f0fcd77e46a6c8f9"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "939427c929ccd1bda65a2766f9fe338e68d58e03"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "32f2cdfa0d17f60b79c110c2e63ab0c2134e6621d36d616a0dd723f359ba6633"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e83f3ed3181dd44ea6dcc507650debd26dbc281"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "2313a9eccf8a65f4fa72595b0a48e7e8b8740f5db57d307cfc221d0e14bcd0c3"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[protoc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e8ea5af5f28f87fb3aedc05382cf98926f3e9a6"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "bc92d687381cc66e3173c2600ad347da78978bccb5530dd204c93d833c086e44"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b85bbe4bfacc66873a98256b14827be4f53c9c04"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "403ba5b6b8a6c711e76b3bd0037d5aabcc0409c32e7c19d95540c9766b364386"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.i686-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5a64f45c720779a0b049e363b8db092636c3b30"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "8320b73a318cf5fe2b23368be99c1f6217c0568e9216b5b071f6062c3f1aa0bb"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.i686-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "acd349255df8cb47a1d483d474ce766b73b6ec30"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "c10c5bd57574ba7f33ca7ac8828525e29954a35def8aa909832cd8b415d39c92"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.i686-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a3678f2a39694edd78daca8350a07fb863cba17"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "7a9816568c6836ffc2d51e0cf5d4f47c656a3bee8b2ea7641c8ea0f83e33491d"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.i686-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a75d1657b934bd7f4ed18d8107ea864109a91db0"
os = "windows"

    [[protoc.download]]
    sha256 = "1d173748d1e9eba41d381063d517475c522224b54b84e88c64839a504355a6c4"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.i686-w64-mingw32-cxx03.tar.gz"
[[protoc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7cf4681a7fb798575ddb988fd5d0ae73765fd4e0"
os = "windows"

    [[protoc.download]]
    sha256 = "c6e4b9ec9106da642530aea19ad57f54618a3744d09cddebf7c9667262b6952d"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.i686-w64-mingw32-cxx11.tar.gz"
[[protoc]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f3225cfb45691a99d629694b4a3d6c4883751c7"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "e30589ea858adeb02ca5cea856bb38a73bef57845e073c2c0e6f110f30e1b949"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c075ba84c9c88f3cbedd25a663854274ee116ea"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "9e0ef9bde7de1eabd0ab43863cd410598ee4dc9bb5b4d15ca90e8e3a6a983494"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "7f828673ccb43785b22a2dfecd699634b267649d"
os = "macos"

    [[protoc.download]]
    sha256 = "3e63cf49d22c51a54c78390509504ac0028ae246b278c9dde94a4e60d771a1af"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.x86_64-apple-darwin.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c54c98a75aee78c196699c429ec383d5bf919beb"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "87828e109b260483530518863027e2ece9e1368189ac74d58494202294f58ecc"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.x86_64-linux-gnu-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5481cfd10fdb1a89ecb6c1305370f4ef87f13c0"
libc = "glibc"
os = "linux"

    [[protoc.download]]
    sha256 = "aba0e44afb26b438ee737039604b59da7868ad4762bee29072f99ea89be8d5eb"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.x86_64-linux-gnu-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "324f6ab229c42fbe7ea39aca41c5d63421d2665e"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "bd3cabb22a765eedb10c74e3b521b5234aa9623a814619b82aa4a25ac58cdebb"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.x86_64-linux-musl-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbc8bc3e18c8647bb02b07e73977b2cb129f516b"
libc = "musl"
os = "linux"

    [[protoc.download]]
    sha256 = "4844d6e88b6d4fa745816668171ee26600a3e20063398cb9ec0eeff7ca6082e0"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.x86_64-linux-musl-cxx11.tar.gz"
[[protoc]]
arch = "x86_64"
git-tree-sha1 = "68de70a8ccb49e0835614089f0a754659320e8ed"
os = "freebsd"

    [[protoc.download]]
    sha256 = "6c3ce43ee119d7dec5c2bc12e9ed031303c053cd20b722201475898f4509c11a"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.x86_64-unknown-freebsd.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6064292fa99a3757203abcd905bdc00573cbee70"
os = "windows"

    [[protoc.download]]
    sha256 = "6265121cd330ef3191cbfd1d24af6c9e7dcfe19e8fdee88bf92edb55ac75ce75"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[protoc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "661f5b16760fb7f2083191f4297020d0bb1effb4"
os = "windows"

    [[protoc.download]]
    sha256 = "5b4735597394d6a2cc55015b4200833cc3c058d4e1c416c39fc5ef31625cd58b"
    url = "https://github.com/JuliaBinaryWrappers/protoc_jll.jl/releases/download/protoc-v3.13.0+0/protoc.v3.13.0.x86_64-w64-mingw32-cxx11.tar.gz"
